version: '3.8'
services:
  sample:
    build:
      context: ../
      dockerfile: ./docker-nginx/Dockerfile
    ports:
      - "2000:80"
    volumes:
      - ../default.conf:/etc/nginx/conf.d/default.conf
