version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./docker-nginx/Dockerfile
    ports:
      - "2000:80"
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  app:
    build: 
      context: .
      dockerfile: ./docker-react/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./docker-react/react/:/app/
      - /app/node_modules
